# Settings
title: Clarity - Making Life Easier!
email: support@clarityapp.co
description: Making Life Easier!
keywords: analytics
baseurl: ""
url: "http://clarityapp.co"

# Links
github: Clarityapp
twitter: claritycohq

# Build settings
markdown: kramdown
