# Settings
title: Clarity - Making Life Easier!
email: support@clarityapp.co
description: Clarity is the only all-in-one financial analysis tool that is geared towards business owners like you. It is easy to use and understand and connects with your favorite online accounting programs Xero and Quickbooks. Join our Beta today!
keywords: analytics
baseurl: ""
url: "http://clarityapp.co"

# Links
github: Clarityapp
twitter: claritycohq

# Build settings
markdown: kramdown
