# Settings
title: Clarity - Making Life Easier!
email: support@clarityapp.co
description: Making Life Easier!
baseurl: ""
url: "http://clarityapp.co"

# Links
github: monkinstudio
dribbble: monkinstudio
twitter: monkinstudio

# Build settings
markdown: kramdown
