# Settings
title: monkin' studio
email: hey@monkinstudio.com
description: Crafting awesome web products & experiences!
baseurl: ""
url: "http://monkinstudio.com"

# Links
github: monkinstudio
dribbble: monkinstudio
twitter: monkinstudio

# Build settings
markdown: kramdown
